### ISSUE TITLE
Add an option to add suffix to exported objects

### ISSUE THREAD

**Issue by Shatur** [BlakeDarrow/EasyExport#32]
It would be convenient to add `_low` and `_high` to object names too. Usually used for mesh baking in Substance Painter (meshes matched by names).

**Comment by BlakeDarrow** [comment]
Also a great suggestion. I have this feature in my other addon, Scene Organizer, but I can see why it would be useful in the exporting context. I'll pull over the code and throw it in the export menu! Thanks for the ideas.

**Comment by Shatur** [comment]
> I have this feature in my other addon, Scene Organizer

If I understand correctly, your Scene Organizer addon renames objects in Blender, but it would be great to keep the original names and just rename them only in the exported `.fbx` files. Since these suffixes are only needed for Substance, it would be nice to keep names in Blender clean.

**Comment by BlakeDarrow** [comment]
Its possible you are using an outdated version, I was misunderstanding you. This feature currently exists within the tool. Either from the pop-up menu (Shortcut E) or the side panel, there is a button called `Use Suffix`. On enabled this will allow you to select `custom`, `_high`, or `_low` as an FBX export suffix. [Here](https://darrow.tools/EasyExport#namingsettings) is a link to the documentation about this feature.

**Comment by Shatur** [comment]
> On enabled this will allow you to select custom, _high, or _low as an FBX export suffix

It adds a suffix for an `.fbx` file. But I meant to add suffix to exported objects inside this file too. Because Substance Painter need it.

**Comment by BlakeDarrow** [comment]
Oh! I see what you're saying, that makes sense now. I didn't think of a use case like that. I'll add this in the next update.

**Comment by BlakeDarrow** [comment]
Added new toggle in suffix panel. Allows either "_high", "_low", or custom string to be added to each exported model. #33
